FROM alpine:3.8 as mybuilder

MAINTAINER Gianmarco Bruno "gianmarco.bruno@ericsson.com"

ENV VERSION=0.4
ENV LIBYANG_VERSION=v0.16-r3

# toolchain
RUN apk update && apk add binutils cmake make libgcc gcc
RUN apk update && apk add musl-dev git pcre pcre-dev
RUN mkdir /opt && cd /opt && \
    git clone https://github.com/CESNET/libyang.git
RUN cd /opt/libyang && git checkout ${LIBYANG_VERSION} && \
    mkdir build && cd build && cmake .. && \
    make && make install

# builder pattern

FROM alpine:3.8

RUN mkdir /root/.yanglint
#RUN mkdir -p /opt/yanglint/build

# to make the build target directory visible
ENV PATH="/opt/libyang/build:${PATH}"

COPY --from=mybuilder /opt/libyang/build/* /opt/libyang/build/
# yanglint libraries
COPY --from=mybuilder /usr/local/lib64/* /usr/local/lib64/
COPY --from=mybuilder /usr/local/lib64/libyang/extensions /usr/local/lib64/libyang/extensions
COPY --from=mybuilder /usr/local/lib64/libyang/user_types /usr/local/lib64/libyang/user_types
# pcre runtime libraries
COPY --from=mybuilder /usr/lib/* /usr/lib/
WORKDIR /opt/yanglint
ENTRYPOINT ["yanglint"]
