FROM alpine:3.8

MAINTAINER Gianmarco Bruno "gianmarco.bruno@ericsson.com"

ENV VERSION=0.3
ENV LIBYANG_VERSION=v0.16-r3

# toolchain
RUN apk update && apk add --no-cache binutils cmake make libgcc gcc
RUN apk update && apk add --no-cache musl-dev git pcre pcre-dev
RUN mkdir /opt && cd /opt && \
    git clone https://github.com/CESNET/libyang.git && \
    cd libyang && git checkout ${LIBYANG_VERSION} && \
    mkdir build && cd build && cmake .. && \
    make && make install

# suppress annoying message at startup
RUN mkdir /root/.yanglint

# to make the build target directory visible
ENV PATH="/opt/libyang/build:${PATH}"

# this is where the volume will be mounted
WORKDIR /opt/yanglint
ENTRYPOINT ["yanglint"]
